INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('The Online World', 'Odd De Presno', 'Wiley', 'English', 352,'2021-02-24 10:00:00', '9781119716020', 22.49, 'Lorem ipsum dolor sit amet, et agam democritum pri. Dolorem ocurreret et eum. Amet malis discere sit et, nostrum disputando no his, debitis moderatius posidonium duo id. Mentitum erroribus mel ei, in usu legere aliquid. An eos augue tation. Sed equidem imperdiet necessitatibus id, integre.', 'The Online World
Chapter 1: Going online will make me rich, right?
We selected "Health" and the "Data Base for Rare diseases." This gave the address of an American foundation for "cysts in kidneys," which is the name of her disease. My wife made contact, and has since received regular reports of research results and experiences gained in the field. We sent an open request for help to an electronic forum for doctors. The result was several useful responses. We searched a magazine data base for medical articles containing the key word "kidney." Paper copies of the most interesting finds arrived by mail after a few days. My wife gave them to her hospital doctor as background reading. Kenya Saikawa is paralyzed. He communicates with his PC and modem using light key strokes and Morse code. Online communications allows Kenya to be in regular contact with people outside the walls of his Tokyo hospital. We met online in a "Handicap Club" on a computer center called TWICS in Tokyo. He was there to exchange experiences with others with disabilities. The club is a personal support group for those in need of help. CompuServe''s Cancer Forum has a similar function. "It''s a blessing that I can visit here 24 hours a day," one visitor said. "When I''m unable to sleep at night, I often sit down by the PC to read and write messages to others." The forum is like a family. The file library is full of information about cancer. Members can just go in there and pick up whatever they want to read. Dave Hughes from Old Colorado Springs, Colorado in the United States has had a long career as a professional soldier. He has fought in places like the Yalue river in Korea and Vietnam''s jungle. When he retired, he became a political online force.' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Bioshock: From Rapture to Columbia', 'Mehdi El Kanafi', 'Third Editions', 'English', 192,'2018-02-20 10:00:00', '9791094723630', 29.90, 'Lorem ipsum dolor sit amet, eam an odio consequuntur, elitr propriae et nam. Euripidis intellegat theophrastus per an, vix ne debet recusabo democritum, in has essent diceret. Ad eum partem primis legendos, sit an tota disputationi mediocritatem. Eum debitis meliore feugait ad. Et vide ludus.', 'Natural Wonders
Chapter 1: How the Chicken Gets Inside the Egg
There is no more fascinating sight to be seen anywhere than an incubator full of eggs just as the chickens begin to hatch out. You look through the little glass window in the side and see, at first, only rows of clean white eggs, dozens upon dozens of them, looking as if they were all ready to go into the family ice-chest or to be made into omelets for breakfast.
But they are not. First you begin to hear faint scratchy sounds. Pretty soon, here and there, a hole breaks through the broad end of an egg, and a tiny bill sticks out. The little chick is packed so tightly into the egg that it can move only its head. So it pecks and pecks; and stops to rest; and pecks again; and the hole in the shell gets larger and larger; until by and by, the egg cracks open, and a brand-new chicken draws its first long breath and looks out into the world.
After that, the chick usually takes a long rest, for it is pretty tired. When it feels better, it begins to move its legs and wings, and a half-hour or more after it first began work, it gets clear of the shell and stands up on wabbly legs, wet, bedraggled, weary, as disconsolate looking a little object as can well be imagined. Shortly, however, the feathers, which at first were plastered tight to the skin, dry off and fluff out, the legs get steady, and soon there is running about a rolypoly yellow chick, seemingly at least twice as large as the egg which held him only an hour before. Truly it is a wonderful sight, five hundred eggs turning into little chicks in an incubator, for all the world like the kernels of corn changing to pop-corn in the popper.
But wonderful as it is to see the way a chick comes out of an egg, it is still more wonderful to see the way it gets in. A fresh, new-laid egg has no chick inside. After it has been kept warm three weeks, it has—all ready to come out. The question is how the chicken got there.
Many different men have studied this question. For the most part, they have started a dozen or more eggs at once, and then taken them one by one and two or three hours apart, and cautiously broken them open to see what was inside. Sometimes, however, a student of eggs carefully cuts away the shell on one side, until he has made a hole about the size of a ten-cent piece. Over this he cements a sheet of glass as thin as paper, so that he can look through this tiny window into the egg, and see the chick grow.' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('We Begin at the End', 'Chris Whitaker', 'Holt, Henry & Company, Inc.', 'English', 384,'2021-03-21 10:00:00', '9781250759672', 14.99, 'Lorem ipsum dolor sit amet, eum te primis reprehendunt. Vix quando concludaturque cu. Impedit elaboraret signiferumque per cu, pri et everti accommodare. Assum essent at nam, qui altera phaedrum id. Per ipsum nusquam postulant eu. At sit elit discere omittantur, nam duis posse dignissim in.', 'The Scarlet Plague
Chapter 1:
THE way led along upon what had once been the embankment of a railroad. But no train had run upon it for many years. The forest on either side swelled up the slopes of the embankment and crested across it in a green wave of trees and bushes. The trail was as narrow as a man''s body, and was no more than a wild-animal runway. Occasionally, a piece of rusty iron, showing through the forest-mould, advertised that the rail and the ties still remained. In one place, a ten-inch tree, bursting through at a connection, had lifted the end of a rail clearly into view. The tie had evidently followed the rail, held to it by the spike long enough for its bed to be filled with gravel and rotten leaves, so that now the crumbling, rotten timber thrust itself up at a curious slant. Old as the road was, it was manifest that it had been of the mono-rail type.
An old man and a boy travelled along this runway. They moved slowly, for the old man was very old, a touch of palsy made his movements tremulous, and he leaned heavily upon his staff. A rude skull-cap of goat-skin protected his head from the sun. From beneath this fell a scant fringe of stained and dirty-white hair. A visor, ingeniously made from a large leaf, shielded his eyes, and from under this he peered at the way of his feet on the trail. His beard, which should have been snow-white but which showed the same weather-wear and camp-stain as his hair, fell nearly to his waist in a great tangled mass. About his chest and shoulders hung a single, mangy garment of goat-skin. His arms and legs, withered and skinny, betokened extreme age, as well as did their sunburn and scars and scratches betoken long years of exposure to the elements.
The boy, who led the way, checking the eagerness of his muscles to the slow progress of the elder, likewise wore a single garment—a ragged-edged piece of bear-skin, with a hole in the middle through which he had thrust his head. He could not have been more than twelve years old. Tucked coquettishly over one ear was the freshly severed tail of a pig. In one hand he carried a medium-sized bow and an arrow.
' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('The Rose Code', 'Kate Quinn', 'William Morrow Paperbacks', 'English', 656,'2021-03-21 10:00:00', '9780062943484', 11.99, 'Lorem ipsum dolor sit amet, id usu semper legimus, sea cu reque quando. Justo nonumy vidisse at sea, putant constituam repudiandae te mea. Ius ei aliquip nominavi deseruisse. Et ipsum putent sea. Sint laudem mea eu, ut usu reque choro commodo. Sit an solum tempor.', 'The Red Fairy Book
Chapter 1: The Twelve Dancing Pricesses
ONCE upon a time there lived in the village of Montignies-sur-Roc a little cow-boy, without either father or mother. His real name was Michael, but he was always called the Star Gazer, because when he drove his cows over the commons to seek for pasture, he went along with his head in the air, gaping at nothing.
As he had a white skin, blue eyes, and hair that curled all over his head, the village girls used to cry after him, ‘Well, Star Gazer, what are you doing?’ and Michael would answer, ‘Oh, nothing,’ and go on his way without even turning to look at them.
The fact was he thought them very ugly, with their sun-burnt necks, their great red hands, their coarse petticoats and their wooden shoes. He had heard that somewhere in the world there were girls whose necks were white and whose hands were small, who were always dressed in the finest silks and laces, and were called princesses, and while his companions round the fire saw nothing in the flames but common everyday fancies, he dreamed that he had the happiness to marry a princess.
' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Klara and the Sun', 'Kazuo Ishiguro', 'Knopf Doubleday Publishing Group', 'English', 320,'2021-03-21 10:00:00', '9780593318171', 11.99, 'Lorem ipsum dolor sit amet, at doctus persius mediocrem usu, assum postea vel cu. Sed et alienum elaboraret disputationi, et saepe facilisi sed. Sit indoctum definitiones ad, at mel minimum deleniti, duo ipsum nulla id. Eam elit vocent mentitum in, pro porro eloquentiam in mea. Ea per quem salutandi consequat, hinc laudem.', 'Sunshine Sketches of a Little Town
Chapter 1: The Hostelry of Mr. Smith
I don''t know whether you know Mariposa. If not, it is of no consequence, for if you know Canada at all, you are probably well acquainted with a dozen towns just like it.
There it lies in the sunlight, sloping up from the little lake that spreads out at the foot of the hillside on which the town is built. There is a wharf beside the lake, and lying alongside of it a steamer that is tied to the wharf with two ropes of about the same size as they use on the Lusitania. The steamer goes nowhere in particular, for the lake is landlocked and there is no navigation for the Mariposa Belle except to "run trips" on the first of July and the Queen''s Birthday, and to take excursions of the Knights of Pythias and the Sons of Temperance to and from the Local Option Townships.
In point of geography the lake is called Lake Wissanotti and the river running out of it the Ossawippi, just as the main street of Mariposa is called Missinaba Street and the county Missinaba County. But these names do not really matter. Nobody uses them. People simply speak of the "lake" and the "river" and the "main street," much in the same way as they always call the Continental Hotel, "Pete Robinson''s" and the Pharmaceutical Hall, "Eliot''s Drug Store." But I suppose this is just the same in every one else''s town as in mine, so I need lay no stress on it.
' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('The Four Winds', 'Kristin Hannah', 'St. Martin''s Publishing Group', 'English', 320,'2021-02-02 10:00:00', '9781250178626', 14.99, 'Lorem ipsum dolor sit amet, ad his quem lorem concludaturque. Ad per aperiam imperdiet. Elitr legimus ullamcorper in quo. No nemore integre vix, no nisl mentitum voluptaria vim. Quo ne tale idque eirmod.', 'The Wind in the Willows
Chapter 1: The River Bank
The Mole had been working very hard all the morning, spring-cleaning his little home. First with brooms, then with dusters; then on ladders and steps and chairs, with a brush and a pail of whitewash; till he had dust in his throat and eyes, and splashes of whitewash all over his black fur, and an aching back and weary arms. Spring was moving in the air above and in the earth below and around him, penetrating even his dark and lowly little house with its spirit of divine discontent and longing. It was small wonder, then, that he suddenly flung down his brush on the floor, said ‘Bother!’ and ‘O blow!’ and also ‘Hang spring-cleaning!’ and bolted out of the house without even waiting to put on his coat. Something up above was calling him imperiously, and he made for the steep little tunnel which answered in his case to the gravelled carriage-drive owned by animals whose residences are nearer to the sun and air. So he scraped and scratched and scrabbled and scrooged and then he scrooged again and scrabbled and scratched and scraped, working busily with his little paws and muttering to himself, ‘Up we go! Up we go!’ till at last, pop! his snout came out into the sunlight, and he found himself rolling in the warm grass of a great meadow.
‘This is fine!’ he said to himself. ‘This is better than whitewashing!’ The sunshine struck hot on his fur, soft breezes caressed his heated brow, and after the seclusion of the cellarage he had lived in so long the carol of happy birds fell on his dulled hearing almost like a shout. Jumping off all his four legs at once, in the joy of living and the delight of spring without its cleaning, he pursued his way across the meadow till he reached the hedge on the further side.
' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('The Kaiser''s Web', 'Steve Berry', 'St. Martin''s Publishing Group', 'English', 400,'2021-02-23 10:00:00', '9781250140357', 14.99, 'Lorem ipsum dolor sit amet, sea vidit omnium dolorem ne, brute aeque congue ut nec, quo regione ornatus tacimates an. Eu eum odio vituperata elaboraret, oratio essent regione vim et, ea pro pertinax platonem aliquando. Nec cu vide ocurreret explicari. Cu mei erat ludus sapientem.', 'Daddy-Long-Legs
Chapter 1: Blue Wednesday
The first Wednesday in every month was a Perfectly Awful Day—a day to be awaited with dread, endured with courage and forgotten with haste. Every floor must be spotless, every chair dustless, and every bed without a wrinkle. Ninety-seven squirming little orphans must be scrubbed and combed and buttoned into freshly starched ginghams; and all ninety-seven reminded of their manners, and told to say, ''Yes, sir,'' ''No, sir,'' whenever a Trustee spoke.
It was a distressing time; and poor Jerusha Abbott, being the oldest orphan, had to bear the brunt of it. But this particular first Wednesday, like its predecessors, finally dragged itself to a close. Jerusha escaped from the pantry where she had been making sandwiches for the asylum''s guests, and turned upstairs to accomplish her regular work. Her special care was room F, where eleven little tots, from four to seven, occupied eleven little cots set in a row. Jerusha assembled her charges, straightened their rumpled frocks, wiped their noses, and started them in an orderly and willing line towards the dining-room to engage themselves for a blessed half hour with bread and milk and prune pudding.' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('The Sanatorium', 'Sarah Pearse', 'Penguin Publishing Group', 'English', 400,'2021-02-02 10:00:00', '9780593296677', 20.99, 'Lorem ipsum dolor sit amet, no dico aliquip accumsan has, an mea esse semper ceteros, perfecto lobortis cu vel. Eum dicta ridens deterruisset ex, et pro vidisse noluisse percipitur. Cum ad adhuc liber delenit, nec ut everti cetero. Ad case inani adipiscing vis, soleat animal.', 'Old Taverns of New York
Chapter 1: Dutch Taverns
On the return of Hendrick Hudson from his voyage of discovery in 1609, his reports were so favorable, especially, as to the abundance of valuable furs which were to be had at very little cost, that several merchants of Amsterdam, without delay, fitted out trading vessels and sent them to trade with the Indians in the territory he had visited. The returns were satisfactory, and they formed themselves into a company under the name of the United Netherland Company and established a trading post on the southern part of Manhattan Island. The exclusive privilege of trade, which had been granted them by Holland, expired in the year 1618, and they endeavored to have the grant renewed or extended, but succeeded only in obtaining a special license, expiring yearly, which they held for two or three years longer.
In the meantime a more extensive association had been formed by some merchants and capitalists of Holland, who in the year 1621 received a charter under the title of the West India Company, which gave to them the exclusive privilege of trade on the whole Atlantic coast, so far as the jurisdiction of Holland extended. Powers of government were conferred upon the company and the right to make treaties with the Indians.' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('A Gambling Man', 'David Baldacci', 'Grand Central Publishing', 'English', 350,'2021-04-20 10:00:00', '9781538719664', 14.99, 'Lorem ipsum dolor sit amet, has id tollit reprehendunt, pro ea percipit qualisque, est id dicit veniam. Essent discere torquatos pro eu, est id dicit habemus deterruisset. Stet perfecto tacimates te vis. Laudem menandri suscipiantur et est, cu ius diceret nominavi. Cu vix tollit numquam.', 'The Gaming Table
Chapter 1: The Universal Passion of Gaming; Or, Gaming All The World Over.
A very apt allegory has been imagined as the origin of Gaming. It is said that the Goddess of Fortune, once sporting near the shady pool of Olympus, was met by the gay and captivating God of War, who soon allured her to his arms. They were united; but the matrimony was not holy, and the result of the union was a misfeatured child named Gaming. From the moment of her birth this wayward thing could only be pleased by cards, dice, or counters.
She was not without fascinations, and many were her admirers. As she grew up she was courted by all the gay and extravagant of both sexes, for she was of neither sex, and yet combining the attractions of each. At length, however, being mostly beset by men of the sword, she formed an unnatural union with one of them, and gave birth to twins—one called DUELLING, and the other a grim and hideous monster named SUICIDE. These became their mother''s darlings, nursed by her with constant care and tenderness, and her perpetual companions.' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('A Time for Mercy', 'John Grisham', 'Knopf Doubleday Publishing Group', 'English', 480,'2020-10-13 10:00:00', '9780385545969', 20.96, 'Lorem ipsum dolor sit amet, vis audiam scripta ea, cu ius postulant adolescens scribentur, vel eu ornatus omittam reformidans. Ea est graecis appellantur. Impetus legendos sit no, no sea quis numquam convenire. Te mel prima altera aperiam. Qui prompta molestiae ea. Iisque voluptaria disputationi no.', 'Mercy Flight
Chapter 1: 
The phone rang and Ed Kerry wasn''t doing anything so he picked it up and said, "Yeah?"
He said yeah a few more times, his eyes widening infinitesimally each time, and finally wound up with, "Okay, Bunny."
He hung up and said, "That was Bunny, up in Oneonta. She says a guy is coming in from Luna with a kid for emergency hospitalization, radiation burns or something."
Jake was sitting back in his swivel chair, his feet on the desk and his hands clasped behind his head. He growled, "That''s the trouble with women in this game; they''ve got no story sense. She phones all the way from Oneonta on a story that''s been run a hundred times. Every time somebody gets good and sick up on Luna they bring ''em to Earth for treatment." He shrugged. "Okay, so it''s a kid this time. Do up about a stick of it, Kerry, and we''ll put it on page three if you can work it into a tear-jerker."
Ed Kerry said, "You didn''t let me finish, Jake. Something''s wrong with this guy''s radio."
Somebody on the rewrite desk said, "Something wrong with his radio? He''s gotta have his radio or he can''t come in."
Jake took his feet from the desk and sat up. "What''d'' ya mean, something''s wrong with his radio?"
"Bunny said he''s calling for his landing instructions but they can''t get anything back to him. He''s just reached Brennschluss and he''s in free fall now; it''ll be four days before he gets here. That''s the way they work it—he''s supposed to get in touch with the spaceport he wants to land at, and...."
"I know how they work it," Jake growled. "See if there''s anything on the last newswire from Luna about him."' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Destination Truth: Memoirs of a Monster Hunter', 'Josh Gates', 'Gallery Books', 'English', 272,'2011-10-11 10:00:00', '9780743491723', 15.99, 'Lorem ipsum dolor sit amet, utroque partiendo mea an, ei eos graece atomorum recteque, sed elit blandit recusabo te. Consetetur voluptatum an per, molestie lucilius reprimique mea eu. An duo summo possim habemus, ne solet omittantur philosophia est, ius ea quidam omnesque fabellas. Corpora consulatu.', 'The Politeness of Princes, and Other School Stories
Chapter 1: 
The painful case of G. Montgomery Chapple, bachelor, of Seymour''s house, Wrykyn. Let us examine and ponder over it.
It has been well said that this is the age of the specialist. Everybody, if they wish to leave the world a better and happier place for their stay in it, should endeavour to adopt some speciality and make it their own. Chapple''s speciality was being late for breakfast. He was late not once or twice, but every day. Sometimes he would scramble in about the time of the second cup of coffee, buttoning his waistcoat as he sidled to his place. Generally he would arrive just as the rest of the house were filing out; when, having lurked hidden until Mr. Seymour was out of the way, he would enter into private treaty with Herbert, the factotum, who had influence with the cook, for Something Hot and maybe a fresh brew of coffee. For there was nothing of the amateur late-breakfaster about Chapple. Your amateur slinks in with blushes deepening the naturally healthy hue of his face, and, bolting a piece of dry bread and gulping down a cup of cold coffee, dashes out again, filled more with good resolutions for the future than with food. Not so Chapple. He liked his meals. He wanted a good deal here below, and wanted it hot and fresh. Conscience had but a poor time when it tried to bully Chapple. He had it weak in the first round.' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Dust in Darkness', 'Eddie Patin', 'Lost Woods Publishing LLC', 'English', 325, '2017-12-29 10:00:00', '2940155426691', 0.00, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'After Dark
Chapter 1: LEAVES FROM LEAH’S DIARY.
26th February, 1827.—The doctor has just called for the third time to examine my husband’s eyes. Thank God, there is no fear at present of my poor William losing his sight, provided he can be prevailed on to attend rigidly to the medical instructions for preserving it. These instructions, which forbid him to exercise his profession for the next six months at least, are, in our case, very hard to follow. They will but too probably sentence us to poverty, perhaps to actual want; but they must be borne resignedly, and even thankfully, seeing that my husband’s forced cessation from work will save him from the dreadful affliction of loss of sight. I think I can answer for my own cheerfulness and endurance, now that we know the worst. Can I answer for our children also? Surely I can, when there are only two of them. It is a sad confession to make, but now, for the first time since my marriage, I feel thankful that we have no more.
17th.—A dread came over me last night, after I had comforted William as well as I could about the future, and had heard him fall off to sleep, that the doctor had not told us the worst. Medical men do sometimes deceive their patients, from what has always seemed to me to be misdirected kindness of heart. The mere suspicion that I had been trifled with on the subject of my husband’s illness, caused me such uneasiness, that I made an excuse to get out, and went in secret to the doctor. Fortunately, I found him at home, and in three words I confessed to him the object of my visit.' );



INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Elizabeth & Margaret: The Intimate World of the Windsor Sisters', 'Andrew Morton', 'Grand Central Publishing', 'English', 384, '2019-03-31 10:00:00', '9781538700464', 23.49, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'Little Women
Chapter 1: Playing Pilgrims
"Christmas won''t be Christmas without any presents," grumbled Jo, lying on the rug.
"It''s so dreadful to be poor!" sighed Meg, looking down at her old dress.
"I don''t think it''s fair for some girls to have plenty of pretty things, and other girls nothing at all," added little Amy, with an injured sniff.
"We''ve got Father and Mother, and each other," said Beth contentedly from her corner.
The four young faces on which the firelight shone brightened at the cheerful words, but darkened again as Jo said sadly, "We haven''t got Father, and shall not have him for a long time." She didn''t say "perhaps never," but each silently added it, thinking of Father far away, where the fighting was.
Nobody spoke for a minute; then Meg said in an altered tone, "You know the reason Mother proposed not having any presents this Christmas was because it is going to be a hard winter for everyone; and she thinks we ought not to spend money for pleasure, when our men are suffering so in the army. We can''t do much, but we can make our little sacrifices, and ought to do it gladly. But I am afraid I don''t," and Meg shook her head, as she thought regretfully of all the pretty things she wanted.
"But I don''t think the little we should spend would do any good. We''ve each got a dollar, and the army wouldn''t be much helped by our giving that. I agree not to expect anything from Mother or you, but I do want to buy Undine and Sintran for myself. I''ve wanted it so long," said Jo, who was a bookworm.
"I planned to spend mine in new music," said Beth, with a little sigh, which no one heard but the hearth brush and kettle-holder.
"I shall get a nice box of Faber''s drawing pencils; I really need them," said Amy decidedly.
"Mother didn''t say anything about our money, and she won''t wish us to give up everything. Let''s each buy what we want, and have a little fun; I''m sure we work hard enough to earn it," cried Jo, examining the heels of her shoes in a gentlemanly manner.' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Every Vow You Break', 'Peter Swanson', 'HarperCollins Publishers', 'English', 320, '2016-02-11 10:00:00', '9780062980038', 22.99, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'Father Goriot
Chapter 1: Father Goriot
Mme. Vauquer (nee de Conflans) is an elderly person, who for the past forty years has kept a lodging-house in the Rue Nueve-Sainte-Genevieve, in the district that lies between the Latin Quarter and the Faubourg Saint-Marcel. Her house (known in the neighborhood as the Maison Vauquer) receives men and women, old and young, and no word has ever been breathed against her respectable establishment; but, at the same time, it must be said that as a matter of fact no young woman has been under her roof for thirty years, and that if a young man stays there for any length of time it is a sure sign that his allowance must be of the slenderest. In 1819, however, the time when this drama opens, there was an almost penniless young girl among Mme. Vauquer’s boarders.
That word drama has been somewhat discredited of late; it has been overworked and twisted to strange uses in these days of dolorous literature; but it must do service again here, not because this story is dramatic in the restricted sense of the word, but because some tears may perhaps be shed intra et extra muros before it is over.
Will any one without the walls of Paris understand it? It is open to doubt. The only audience who could appreciate the results of close observation, the careful reproduction of minute detail and local color, are dwellers between the heights of Montrouge and Montmartre, in a vale of crumbling stucco watered by streams of black mud, a vale of sorrows which are real and joys too often hollow; but this audience is so accustomed to terrible sensations, that only some unimaginable and well-neigh impossible woe could produce any lasting impression there. Now and again there are tragedies so awful and so grand by reason of the complication of virtues and vices that bring them about, that egotism and selfishness are forced to pause and are moved to pity; but the impression that they receive is like a luscious fruit, soon consumed. Civilization, like the car of Juggernaut, is scarcely stayed perceptibly in its progress by a heart less easy to break than the others that lie in its course; this also is broken, and Civilization continues on her course triumphant. And you, too, will do the like; you who with this book in your white hand will sink back among the cushions of your armchair, and say to yourself, “Perhaps this may amuse me.” You will read the story of Father Goriot’s secret woes, and, dining thereafter with an unspoiled appetite, will lay the blame of your insensibility upon the writer, and accuse him of exaggeration, of writing romances. Ah! once for all, this drama is neither a fiction nor a romance! All is true,—so true, that every one can discern the elements of the tragedy in his own house, perhaps in his own heart.' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Realm Breaker', 'Victoria Aveyard', 'HarperCollins Publishers', 'English', 576, '2015-05-04 10:00:00', '9780062872623', 15.99, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'A Monk of Fife
Chapter 1: HOW THIS BOOK WAS WRITTEN, AND HOW NORMAN LESLIE FLED OUT OF FIFE
It is not of my own will, nor for my own glory, that I, Norman Leslie, sometime of Pitcullo, and in religion called Brother Norman, of the Order of Benedictines, of Dunfermline, indite this book.  But on my coming out of France, in the year of our Lord One thousand four hundred and fifty-nine, it was laid on me by my Superior, Richard, Abbot in Dunfermline, that I should abbreviate the Great Chronicle of Scotland, and continue the same down to our own time. {1}  He bade me tell, moreover, all that I knew of the glorious Maid of France, called Jeanne la Pucelle, in whose company I was, from her beginning even till her end.
Obedient, therefore, to my Superior, I wrote, in this our cell of Pluscarden, a Latin book containing the histories of times past, but when I came to tell of matters wherein, as Maro says, “pars magna fui,” I grew weary of such rude, barbarous Latin as alone I am skilled to indite, for of the manner Ciceronian, as it is now practised by clerks of Italy, I am not master: my book, therefore, I left unfinished, breaking off in the middle of a sentence.  Yet, considering the command laid on me, in the end I am come to this resolve, namely, to write the history of the wars in France, and the history of the blessed Maid (so far at least as I was an eyewitness and partaker thereof), in the French language, being the most commonly understood of all men, and the most delectable.  It is not my intent to tell all the story of the Maid, and all her deeds and sayings, for the world would scarcely contain the books that should be written.  But what I myself beheld, that I shall relate, especially concerning certain accidents not known to the general, by reason of which ignorance the whole truth can scarce be understood.  For, if Heaven visibly sided with France and the Maid, no less did Hell most manifestly take part with our old enemy of England.  And often in this life, if we look not the more closely, and with the eyes of faith, Sathanas shall seem to have the upper hand in the battle, with whose very imp and minion I myself was conversant, to my sorrow, as shall be shown.' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Brood', 'Jackie Polzin', 'Knopf Doubleday Publishing Group', 'English', 240, '2014-01-14 10:00:00', '9780385546751', 19.99, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'In the Brooding Wild
Chapter 1: On the Mountainside
To the spirit which broods over the stupendous solitudes of the northern Rockies, the soul of man, with all its complex impulses, is but so much plastic material which it shapes to its own inscrutable ends. For the man whose lot is cast in the heart of these wilds, the drama of life usually moves with a tremendous simplicity toward the sudden and sombre tragedy of the last act. The titanic world in which he lives closes in upon him and makes him its own. For him, among the ancient watch-towers of the earth, the innumerable interests and activities of swarming cities, the restless tides and currents of an eager civilization, take on the remoteness of a dream. The peace or war of nations is less to him 
2
than the battles of Wing and Fur. His interests are all in that world over which he seeks to rule by the law of trap and gun, and in the war of defence which he wages against the aggression of the elements. He returns insensibly to the type of the primitive man, strong, patient, and enduring.
High up on the mountainside, overlooking a valley so deep and wide as to daze the brain of the gazing human, stands a squat building. It seems to have been crushed into the slope by the driving force of the vicious mountain storms to which it is open on three sides. There is no shelter for it. It stands out bravely to sunshine and storm alike with the contemptuous indifference of familiarity. It is a dugout, and, as its name implies, is built half in the ground. Its solitary door and single parchment-covered window overlook the valley, and the white path in front where the snow is packed hard by the tramp of dogs and men, and the runners of the dog-sled. Below the slope bears away to the woodlands. Above the hut the overshadowing mountain rises to dazzling heights; and a further, but thin, belt of primeval forest extends up, up, until the eternal snows are reached and the air will no longer support life. Even to the hardy hunters, whose home this is, those upper forests are sealed chapters in Nature’s story.
' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('How Beautiful We Were', 'Imbolo Mbue', 'Random House Publishing Group', 'English', 384, '2018-09-03 10:00:00', '9780593132425', 23.49, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'Black Beauty
Chapter 1: My Early Home
The first place that I can well remember was a large pleasant meadow with a pond of clear water in it. Some shady trees leaned over it, and rushes and water-lilies grew at the deep end. Over the hedge on one side we looked into a plowed field, and on the other we looked over a gate at our master''s house, which stood by the roadside; at the top of the meadow was a grove of fir trees, and at the bottom a running brook overhung by a steep bank.
While I was young I lived upon my mother''s milk, as I could not eat grass. In the daytime I ran by her side, and at night I lay down close by her. When it was hot we used to stand by the pond in the shade of the trees, and when it was cold we had a nice warm shed near the grove.
As soon as I was old enough to eat grass my mother used to go out to work in the daytime, and come back in the evening.
There were six young colts in the meadow besides me; they were older than I was; some were nearly as large as grown-up horses. I used to run with them, and had great fun; we used to gallop all together round and round the field as hard as we could go. Sometimes we had rather rough play, for they would frequently bite and kick as well as gallop.
One day, when there was a good deal of kicking, my mother whinnied to me to come to her, and then she said:
“I wish you to pay attention to what I am going to say to you. The colts who live here are very good colts, but they are cart-horse colts, and of course they have not learned manners. You have been well-bred and well-born; your father has a great name in these parts, and your grandfather won the cup two years at the Newmarket races; your grandmother had the sweetest temper of any horse I ever knew, and I think you have never seen me kick or bite. I hope you will grow up gentle and good, and never learn bad ways; do your work with a good will, lift your feet up well when you trot, and never bite or kick even in play.”
' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Girl A', 'Abigail Dean', 'Penguin Publishing Group', 'English', 352, '2012-06-15 10:00:00', '9780593295847', 19.99, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'Maggie: A Girl of the Streets
Chapter 1:
A very little boy stood upon a heap of gravel for the honor of Rum Alley. He was throwing stones at howling urchins from Devil''s Row who were circling madly about the heap and pelting at him.
His infantile countenance was livid with fury. His small body was writhing in the delivery of great, crimson oaths.
"Run, Jimmie, run! Dey''ll get yehs," screamed a retreating Rum Alley child.
"Naw," responded Jimmie with a valiant roar, "dese micks can''t make me run."
Howls of renewed wrath went up from Devil''s Row throats. Tattered gamins on the right made a furious assault on the gravel heap. On their small, convulsed faces there shone the grins of true assassins. As they charged, they threw stones and cursed in shrill chorus.
The little champion of Rum Alley stumbled precipitately down the other side. His coat had been torn to shreds in a scuffle, and his hat was gone. He had bruises on twenty parts of his body, and blood was dripping from a cut in his head. His wan features wore a look of a tiny, insane demon.
On the ground, children from Devil''s Row closed in on their antagonist. He crooked his left arm defensively about his head and fought with cursing fury. The little boys ran to and fro, dodging, hurling stones and swearing in barbaric trebles.
From a window of an apartment house that upreared its form from amid squat, ignorant stables, there leaned a curious woman. Some laborers, unloading a scow at a dock at the river, paused for a moment and regarded the fight. The engineer of a passive tugboat hung lazily to a railing and watched. Over on the Island, a worm of yellow convicts came from the shadow of a building and crawled slowly along the river''s bank.
' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('The Palm Beach Murders', 'James Patterson', 'Grand Central Publishing', 'English', 396, '2010-10-23 10:00:00', '9781538749982', 13.49, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'The Palm Beach Murders
Chapter One
I somehow managed to slide onto a stool at one of the prime high-top tables near the front of the door of the Palm Beach Grill. From here you could see the bar, get waited on easily, and keep an eye out for anyone of note who wandered through the main entrance. Landing this high-top was close to a miracle on a Friday evening at seven o’clock, when the place was clogged with Palm Beachers. Julie, the sweet personable maitre d’, stopped by, and I gave her a hug.
I needed a night out and a few laughs with my friend Lisa Martz. Like me, Lisa was going through a rough divorce, but she’d hit the ground running and never looked back. The whole thing had struck me a little harder, mainly because it had come out of left field. Lisa was happy to be out of her prison, whereas I’d never thought I was in one.
' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('The Red Book', 'James Patterson', 'Little, Brown and Company', 'English', 400, '2020-07-29 10:00:00', '9780316499408', 20.99, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'The Red book
Chapter One
LIGHTS, CAMERA, action.
This could mean everything to Latham. It could be his ticket out.
But it could ruin him, too. It could land him in prison.
Or worse. It’s the “worse” that jars him awake in the middle of the night, heart pounding, bedsheets soaked in sweat.
    Their driver tried to jam the vehicle into reverse. But it was too late. The vehicle behind them was already burning, hit by an anti-tank missile, and stMarcus knew they were next.
    “Get out,” he ordered his team. “Everybody out--now!”
' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('The Beirut Protocol (Marcus Ryker Series #4)', 'Joel C. Rosenberg', 'Tyndale House Publishers', 'English', 464, '2009-03-09 10:00:00', '9781496437891', 20.99, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'The Beirut Protocol (Marcus Ryker Series #4)');

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Masked Prey (Lucas Davenport Series #30)', 'John Sandford', 'Penguin Publishing Group', 'English', 432, '2006-02-09 10:00:00', '9780593328576', 14.99, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'Masked Prey (Lucas Davenport Series #30)
Chapter One
Audrey Coil and Blake Winston had been sexting each other for weeks.
Winston’s penis, of which Coil had seen perhaps seven or eight iPone views in a variety of penile moods, was not clearly different than the penises of a dozen other classmates that Coil had seen, circulated through the smartphones operated by girls in their final year at The Claridge School--a school with the capital-T in “The,” so it wasn’t some Claridge School, it was The Claridge School, of Reston, Virginia.'  );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Bone-a-fied Trouble', 'Carolyn Haines', 'Carolyn Haines, Inc.', 'English', 300, '2006-06-14 10:00:00', '9780984700134', 9.99, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'Bone-a-fied Trouble
Chapter One
I smell money! I’ve heard the expression all my life and thought it was an exaggeration of the rapacious American spirit of Manifest Destiny. Not true! I, quite literally, smell it. It’s the odor of this rich Delta soil being turned over by the big machines plowing and planting. Another money crop is going into the Mississippi alluvial ground, as
nd yes, now I understand what money smells like. Something to keep in mind as I learn my way around Sunflower County in Mississippi.
    I’m here on a mission. A fellow feline, Pluto Delaney, has called me in to assist him in resolving a mystery. Pluto needs to find a missing female humanoid. Trudy Wells belongs to one sassy little marmalade kitty named Vesta, and Vesta is missing her human. Pluto has a thing for Vesta, and I’m here to help. Nothing flips my ascot as much as a mystery given to me by a black cat almost as eloquent and articulate as I--a mystery that also involves a missing person. If anyone can find the missing girl, I’m that bloke.
' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('They Both Die at the End', 'Adam Silvera', 'HarperCollins Publishers', 'English', 416, '2018-12-18 10:00:00', '9780062457806', 10.99, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'They Both Die at the End
September 5, 2017
Mateo Torrez
12:22 a.m.
Death-Cast is calling with the warning of a lifetime--I’m going to die today. Forget that, “warning” is too strong a word since warnings suggest something can be avoided, like a car honking at someone who’s crossing the street when it isn’t their light, giving them the chance to step back; this is more of a heads-up. The alert, a distinctive and endless gong, like a church bell one block away, is blasting from my phone on the other side of the room. I’m freaking out already, a hundred thoughts immediately drowning out everything around me. I bet this chaos is what a first-time skydiver feels as she’s plummeting out of a plane, or a pianist playing his first concert. Not that I will ever know for sure.
' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Caste (Oprah''s Book Club): The Origins of Our Discontents', 'Isabel Wilkerson', 'Random House Publishing Group', 'English', 496, '2020-08-04 10:00:00', '9780593230251', 23.99, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'Caste (Oprah''s Book Club): The Origins of Our Discontents
Introduction
What is Caste?
“Caste is the foundation of our divisions,” Isabel Wilkerson writes : The Origins of Our Discontents. Standing resembles the bones of an old house, “the studs and joists that we can’t find in the physical structures we call home.” It is additionally similar to “our bones, the auxiliary honest of our innards kept generally imperceptible without X-beam. Caste/Position/rank in this narrative resembles a nitty gritty clinical history. “Station is a sickness.” It is a languid toxic substance, “an intravenous trickle to the psyche,” supporting a “safe framework” that is likewise powerless against its “poisons.” 
' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('The Song of Achilles', 'Madeline Miller', 'HarperCollins Publishers', 'English', 416, '2012-08-28 10:00:00', '9780062060624', 13.99, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'The Song of Achilles
Introduction:
HOMER, THE FATHER OF POETRY.
In this book we are to tell the story of Troy, and particularly of the famous siege which ended in the total destruction of that renowned city. It is a story of brave warriors and heroes of 3000 years ago, about whose exploits the greatest poets and historians of ancient times have written. Some of the wonderful events of the memorable siege are related in a celebrated poem called the Ilʹi-ad, written in the Greek language. The author of this poem was Hoʹmer, who was the author of another great poem, the Odʹys-sey, which tells of the voyages and adventures of the Greek hero, U-lysʹses, after the taking of Troy.
Homer has been called the Father of Poetry, because he was the first and greatest of poets. He lived so long ago that very little is known about him. We do not even know for a certainty when or where he was born. It is believed, however, that he lived in the ninth century before Christ, and that his native place was Smyrʹna, in Asia Minor. But long after his death several other cities claimed the honor of being his birthplace.' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Firefly Lane', 'Kristin Hannah', 'St. Martin''s Publishing Group', 'English', 528, '2009-01-06 10:00:00', '9780312537074', 14.99, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.','Firefly Lane
Chapter One
They used to be called the Firefly Lane girls. That was a long time ago--more than three decades--but just now, as she lay in bed listening to a winter storm raging outside, it seemed like yesterday.
    In the past week (unquestionably the worst seven days of her life), she’d lost the ability to distance herself from the memories. Too often lately in her dreams it was 1974; she was a teenager again, coming of age in the shadow of a lost war, riding her bike beside her best friend in the darkness so complete it was like being invisible. The place was relevant only as a reference point, but she remembered it in vivid detail: a meandering ribbon of asphalt bordered on either side by gullies of murky water and hillsides of shaggy grass. Before they met, that road seemed to go nowhere at all; it was just a country lane named after an inset no one had ever seen in this rugged blue and green corner of the world.
' );

INSERT INTO book (title, author, publisher, language, pages, publish_date, isbn, price, description, sample)
VALUES ('Firekeeper''s Daughter', 'Angeline Boulley', 'Henry Holt and Co. (BYR)', 'English', 496, '2021-03-16 10:00:00', '9781250766564', 14.99, 'Lorem ipsum dolor sit amet, minimum voluptatibus et vix, ei quo debet dolorum constituam. His cu debitis minimum intellegat, te populo sadipscing sit. Mel te diam cibo probatus, vix no sumo dissentiet. Te lorem commune theophrastus pri, vim et detracto officiis. Simul omnium fabulas et.', 'Firekeeper''s Daughter
Chapter 1
The Amateur
"I ain''t sayin'' as how I could run a whole fire, same as some of the chiefs do; but when it comes to drivin'' an engine, Dan Roberts, an'' doin'' it in time to get the first water, or layin'' hose, I wouldn''t knuckle down to the biggest man in the Department."
"Now see here, Seth Bartlett, what''s the sense of talkin'' that way? It would be a good deal better, an'' I ain''t the only one who says it, if you''d stick right to shinin'', an'' stop playin'' fireman, for that''s ''bout the biggest part of the work you do."
"Do you s''pose I count on shinin'' boots for a livin'' all my life?"
"You''ve got to make a better fist at it than you have done for a year or more, else you''ll never get into anythin'' else. I tell you what it is, Seth Bartlett, when a man wants to hire a boy, he ain''t pickin'' out the feller that''s failed up two or three times over; but he generally looks for the one what'' makin'' a go of it, whether it''s shinin'' or sellin'' papers."
"I ain''t sayin'' but you''re right, Dan, an'' I s''pose it''s a good thing for you to keep right on rememberin''; but it''s different with me. I don''t count on any one man hirin'' me when I strike out for somethin'' better''n shinin''."
"Oh, you don''t, eh? What little game have you got? Goin'' to run a bank, or keep a hotel, or do somethin'' like that?"
"You think you''re funny, but you ain''t. I''m goin'' into the Fire Department when the right time comes, an'' don''t you make any mistake about it."');



INSERT INTO book_status (status_desc) VALUES ('Editor''s Choice');
INSERT INTO book_status (status_desc) VALUES ('Most Popular');
INSERT INTO book_status (status_desc) VALUES ('Monthly Specials');
INSERT INTO book_status (status_desc) VALUES ('Special Weekly Deals');
INSERT INTO book_status (status_desc) VALUES ('Books of the Month');

INSERT INTO genre (genre_desc) VALUES ('Sci-Fi');
INSERT INTO genre (genre_desc) VALUES ('Thriller');
INSERT INTO genre (genre_desc) VALUES ('Non-Fiction');
INSERT INTO genre (genre_desc) VALUES ('Fiction');
INSERT INTO genre (genre_desc) VALUES ('Fantasy');
INSERT INTO genre (genre_desc) VALUES ('Drama');
INSERT INTO genre (genre_desc) VALUES ('History');
INSERT INTO genre (genre_desc) VALUES ('Mystery');
INSERT INTO genre (genre_desc) VALUES ('Action');
