UPDATE audio_samples SET path='audio/TheOnlineWorld.mp3' WHERE id=1;
UPDATE audio_samples SET path='audio/BioshockFromRapturetoColumbia.mp3' WHERE id=2;
UPDATE audio_samples SET path='audio/WeBeginattheEnd.mp3' WHERE id=3;
UPDATE audio_samples SET path='audio/TheFourWinds.mp3' WHERE id=4;
UPDATE audio_samples SET path='audio/DestinationTruthMemoirsofaMonsterHunter.mp3' WHERE id=5;
UPDATE audio_samples SET path='audio/TheKaisersWeb.mp3' WHERE id=6;
UPDATE audio_samples SET path='audio/TheSanatorium.mp3' WHERE id=7;
UPDATE audio_samples SET path='audio/KlaraandtheSun.mp3' WHERE id=8;
UPDATE audio_samples SET path='audio/DustinDarkness.mp3' WHERE id=9;
UPDATE audio_samples SET path='audio/FirekeepersDaughter.mp3' WHERE id=10;
UPDATE audio_samples SET path='audio/FireflyLane.mp3' WHERE id=11;
UPDATE audio_samples SET path='audio/TheSongofAchilles.mp3' WHERE id=12;
UPDATE audio_samples SET path='audio/CasteOprahsBookClubTheOriginsofOurDiscontents.mp3' WHERE id=13;
UPDATE audio_samples SET path='audio/TheRoseCode.mp3' WHERE id=14;
UPDATE audio_samples SET path='audio/TheyBothDieattheEnd.mp3' WHERE id=15;
UPDATE audio_samples SET path='audio/BoneafiedTrouble.mp3' WHERE id=16;
UPDATE audio_samples SET path='audio/MaskedPreyLucasDavenportSeries30.mp3' WHERE id=17;
UPDATE audio_samples SET path='audio/TheBeirutProtocolMarcusRykerSeries4.mp3' WHERE id=18;
UPDATE audio_samples SET path='audio/TheRedBook.mp3' WHERE id=19;
UPDATE audio_samples SET path='audio/ThePalmBeachMurders.mp3' WHERE id=20;
UPDATE audio_samples SET path='audio/GirlA.mp3' WHERE id=21;
UPDATE audio_samples SET path='audio/HowBeautifulWeWere.mp3' WHERE id=22;
UPDATE audio_samples SET path='audio/RealmBreaker.mp3' WHERE id=24;
UPDATE audio_samples SET path='audio/EveryVowYouBreak.mp3' WHERE id=25;
UPDATE audio_samples SET path='audio/ElizabethMargaretTheIntimateWorldoftheWindsorSisters.mp3' WHERE id=26;
UPDATE audio_samples SET path='audio/ATimeforMercy.mp3' WHERE id=27;
UPDATE audio_samples SET path='audio/AGamblingMan.mp3' WHERE id=28;

UPDATE audio_samples SET path='audio/The Online World_v2.mp3' WHERE id=29;
UPDATE audio_samples SET path='audio/Natural Wonders_v2.mp3' WHERE id=30;

UPDATE audio_samples SET path='audio/TheOnlineWorld_v3.mp3' WHERE id=31;
UPDATE audio_samples SET path='audio/NaturalWonders_v3.mp3' WHERE id=32;
UPDATE audio_samples SET path='audio/TheScarletPlague_v3.mp3' WHERE id=33;
UPDATE audio_samples SET path='audio/TheRedFairyBook_v3.mp3' WHERE id=34;
UPDATE audio_samples SET path='audio/SunshineSketchesofaLittleTown_v3.mp3' WHERE id=35;
UPDATE audio_samples SET path='audio/TheWindintheWillows_v3.mp3' WHERE id=36;
UPDATE audio_samples SET path='audio/DaddyLongLegs_v3.mp3' WHERE id=37;
UPDATE audio_samples SET path='audio/ThePolitenessofPrincesandOtherSchoolStories_v3.mp3' WHERE id=38;
UPDATE audio_samples SET path='audio/TheGamingTable_v3.mp3' WHERE id=39;
UPDATE audio_samples SET path='audio/OldTavernsofNewYork_v3.mp3' WHERE id=40;
UPDATE audio_samples SET path='audio/MercyFlight_v3.mp3' WHERE id=41;
UPDATE audio_samples SET path='audio/AfterDark_v3.mp3' WHERE id=42;
UPDATE audio_samples SET path='audio/LittleWomen_v3.mp3' WHERE id=43;
UPDATE audio_samples SET path='audio/FatherGoriot_v3.mp3' WHERE id=44;
UPDATE audio_samples SET path='audio/AMonkofFife_v3.mp3' WHERE id=45;
UPDATE audio_samples SET path='audio/IntheBroodingWild_v3.mp3' WHERE id=46;
UPDATE audio_samples SET path='audio/BlackBeauty_v3.mp3' WHERE id=47;
UPDATE audio_samples SET path='audio/MaggieAGirloftheStreets_v3.mp3' WHERE id=48;
UPDATE audio_samples SET path='audio/TheMurderontheLinks_v3.mp3' WHERE id=49;
UPDATE audio_samples SET path='audio/TheRedRecord_v3.mp3' WHERE id=50;

UPDATE audio_samples SET path='audio/TheProtocolsandWorldRevolution_v3.mp3' WHERE id=51;
UPDATE audio_samples SET path='audio/TheManintheIronMask_v3.mp3' WHERE id=52;
UPDATE audio_samples SET path='audio/TheMuleBone_v3.mp3' WHERE id=53;
UPDATE audio_samples SET path='audio/TheWorldasWillandIdeaVol1of3_v3.mp3' WHERE id=54;
